### ISSUE TITLE
Ref in responses-headers

### ISSUE THREAD

**Issue by pavellr** [philosowaffle/vs-openapi-designer#12]
I have several paths, for example, /test1 and /test2
in the response / headers block I use a reference to an external file (headerParams.yaml)
parameters are only allowed for test1 path
main file:
[index.yaml](https://github.com/philosowaffle/vs-openapi-designer/files/2378141/index.txt)
external Headers params:
[headerParams.yaml](https://github.com/philosowaffle/vs-openapi-designer/files/2378142/headerParams.txt)
result:
[openapi.yaml](https://github.com/philosowaffle/vs-openapi-designer/files/2378140/openapi.txt)

**Comment by philosowaffle** [comment]
[Branch](https://github.com/philosowaffle/vs-openapi-designer/tree/issue/issue_12
) created for investigation.
Current Hypothesis:
- invalid json-ref OR
- Bug in [json-schema-ref-parser](https://github.com/BigstickCarpet/json-schema-ref-parser)

**Comment by pavellr** [comment]
@philosowaffle, Ok, I'll check on Monday and answer you

**Comment by pavellr** [comment]
@philosowaffle It`s works correctly. Thanks.

**Comment by philosowaffle** [comment]
Fix has been released.
