### ISSUE TITLE
preview in browser not working

### ISSUE THREAD

**Issue by tuxedo0801** [philosowaffle/vs-openapi-designer#23]
I'm running latest vscode und debian linux and having problems opening the "preview in browser" feature. Nothing happens, no log output on extension console. 
Any ideas on how to fix this or get more details about the issue?

br,
Alex

**Comment by philosowaffle** [comment]
Found the issue and have [released](https://github.com/philosowaffle/vs-openapi-designer/releases/tag/0.2.2) a fix.

Should be available in the VS Code Marketplace shortly.
