### ISSUE TITLE
Add compatibility for Path templating

### ISSUE THREAD

**Issue by NathanHuisman** [philosowaffle/vs-openapi-designer#25]
The official specification describes:
> There are There are four possible parameter locations specified by the in field:
>
> - path - Used together with Path Templating, where the parameter value is actually part of the operation's URL. This does not include the host or base path of the API. For example, in /items/{itemId}, the path parameter is itemId.
> - query - Parameters that are appended to the URL. For example, in /items?id=###, the query parameter is id.
> - header - Custom headers that are expected as part of the request. Note that RFC7230 states header names are case insensitive.
> - cookie - Used to pass a specific cookie value to the API.

[(here)](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#parameter-locations)

while I get an error:
> Schema error at paths['/auth/{endpoint}'].get.parameters[0].in
> should be equal to one of the allowed values
> allowedValues: query, header, cookie
> Jump to line 117

So this implementation only supports the query, header, and cookie values, and not the path parameter type
I use this a lot, so it would be nice if it would be added.

**Comment by philosowaffle** [comment]
Schema validation is provided by the official [swagger-editor-dist](https://www.npmjs.com/package/swagger-editor-dist) and is not managed by this project.

Without an example schema provided it is difficult to try and recreate what you may be encountering.  However, I did find [this open issue](https://github.com/swagger-api/swagger-editor/issues/1853) on the swagger-editor-dist that seems related to what you are seeing.  Specifically you may find [this comment](https://github.com/swagger-api/swagger-editor/issues/1853#issuecomment-410233531) helpful.

As per the [docs](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-10):

> required - Determines whether this parameter is mandatory. If the parameter location is "path", this property is REQUIRED and its value MUST be true. Otherwise, the property MAY be included and its default value is false.

When I set `required` to FALSE, I get the error you described, but if I set it to TRUE, then the error message goes away.

Ultimately, this misleading error message will need to be resolved by the swagger-editor-dist project.
