### ISSUE TITLE
In-app preview API removed in Insiders build

### ISSUE THREAD

**Issue by daogilvie** [philosowaffle/vs-openapi-designer#33]
Hi, thanks for such a great extension!

Just as a heads up, in the latest stable there is a warning on the in-editor pane that says
```
Extension ‘philosowaffle.openapi-designer’ uses the ‘vscode.previewHtml’ command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code’s webview API.
```

I can confirm in Version 1.33.0-insider (1.33.0-insider) that the in-app preview doesn't work at all, but browser works fine. I have v0.2.3 of the extension installed.

**Comment by philosowaffle** [comment]
Duplicate of #28 .

**Comment by daogilvie** [comment]
Ah apologies, I saw the title of the other issue and assumed it didn't also cover the preview case. Thanks! 👍
